.gitignore
package/i18n/README.md
package/i18n/package.json
package/i18n/src/core.ts
package/i18n/src/i18n.ts
package/i18n/src/type.ts
package/i18n/tsconfig.json
package/signal/src/signal.ts
package/signal/src/type.ts
tsconfig.json

Making @vatr/i18n base on signal.
What kind of change does this PR introduce?

New package for i18n/l10n

---

package/logger/src/logger.ts

perf(logger): refactor making logger object
Fixes #82

perf(logger): refactor making logger object

---

.github/workflows/tests.yml
.github/workflows/verify.yml

feat(workflow): add verify workflow

---

.github/workflows/tests.yml
package/math/README.md
package/math/package.json
package/math/src/math.ts
package/math/src/type.ts
package/math/tsconfig.json

Simple useful Math library written in tiny TypeScript module.

New package: @alwatr/math

---

demo/signal/index.html
demo/signal/index.ts
package/signal/src/signal.ts

Promise to multi requests works

[Signal] Fix multi request and add demo

---

demo/router/index.html
demo/router/index.ts
package/signal/src/core.ts

[remove once listene in dispatch change imediatly the loop!](https://github.com/AliMD/alwatr/commit/e4d420d3a086558dc01dcd7a9c5fe3e96677f092)

Fix signal _dispatchSignal/__callListeners issue

---

package/router/src/router.ts
package/router/src/type.ts

- Improve documents
- define signal as soon as posible

Enhance router: Improve documents, define signal as soon as posible

---

package/i18n/src/i18n.ts
package/i18n/src/signal.ts

Fix direct accesing to the signals

fix(i18n): access signal issue

---

package/router/README.md

docs(router): full example with lit

docs(router): full example with lit

---

packages/core/micro-server/src/micro-server.ts
packages/core/micro-server/src/type.ts
packages/starter/microservice/src/route/echo.ts
packages/starter/microservice/src/route/home.ts

Make a change in the type of `ReplySuccessContent`

feat(micro-server): make  `statusCode` in `ReplySuccessContent` optional

---

packages/core/i18n/src/core.ts
packages/core/i18n/src/i18n.ts
packages/core/i18n/src/type.ts

fix(i18n): load resources issue

---

CHANGELOG.md
README.md
demo/CHANGELOG.md
demo/storage/big-data-test.ts
demo/storage/index.ts
demo/tsconfig.json
lerna.json
packages/core/element/CHANGELOG.md
packages/core/fetch/CHANGELOG.md
packages/core/i18n/CHANGELOG.md
packages/core/i18n/src/core.ts
packages/core/i18n/src/type.ts
packages/core/logger/CHANGELOG.md
packages/core/math/CHANGELOG.md
packages/core/micro-server/CHANGELOG.md
packages/core/router/CHANGELOG.md
packages/core/signal/CHANGELOG.md
packages/core/storage/README.md
packages/core/storage/src/storage.ts
packages/core/storage/src/type.ts
packages/core/storage/tsconfig.json
packages/starter/microservice/CHANGELOG.md
packages/ui/font/CHANGELOG.md

Add `@alwatr/storage` API documention

Storage: add API doc

---

packages/core/nano-server/src/nano-server.ts
packages/starter/nanoservice/.eslintrc.json

- fix a bug of nano server
- set eslint configuration of `nano service` starter

Fix nano server/service requetBody and lint issue

---

packages/lab/wordpress/deploy.sh
packages/service/adminer/deploy.sh
packages/service/mariadb/deploy.sh
packages/service/traefik-proxy/deploy.sh

Add multi .env file support to deploy script

---

packages/core/router/README.md

Fixes #(issue) spelling mistake

Fix(core/router/readme) : spelling mistake

---

packages/core/element/src/element.ts
packages/core/i18n/src/i18n.ts
packages/core/logger/src/logger.ts
packages/core/math/src/math.ts
packages/core/router/src/core.ts
packages/core/router/src/router.ts
packages/core/router/src/signal.ts
packages/core/router/src/trigger-click.ts
packages/core/router/src/trigger-popstate.ts
packages/core/signal/src/core.ts
packages/core/signal/src/signal.ts
packages/core/storage/src/provider.ts

Add mime type in imports
Fixes #324

fix: Import error in webpack

---

packages/core/storage/README.md

docs(storage): update readme

---

packages/core/fetch/README.md
packages/core/fetch/src/fetch.ts

fix(fetch): _handleRemoveDuplicate

---

demo/fetch/index.ts
packages/core/fetch/README.md
packages/core/fetch/src/fetch.ts

feat(fetch): revalidate callback for `stale_while_revalidate` cache strategy.

---

ui/demo-pwa/src/alwatr-page-home.ts
ui/element/src/mixins/signal.ts

fix(ui/element): listener list type

---

ui/demo-pwa/src/page-chat.ts
ui/ui-kit/package.json
ui/ui-kit/src/chat/chat-list.ts
ui/ui-kit/tsconfig.json

feat(chat-list): new element for list of chats

---

core/router/src/trigger-click.ts

preventDefault on SVG link click
Fixes #590 
- [ * ] Open an issue for bug report or feature request and mention it to this PR.
- [ * ] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [ * ] I have performed a self-review of my own code.

fix(core/router): preventDefault on svg link click

---

ui/demo-pwa/src/page-chat.ts
ui/demo-pwa/style/tokens/state.css
ui/ui-kit/src/icon-button/standard-icon-button.ts

feat(ui-kit/icon-button): new component

---

ui/icon/src/icon.ts

feat(ui/icon): direction mixin

---

ui/ui-kit/src/icon-button/standard-icon-button.ts

feat(ui-kit/icon-button): icon flip-rtl

---

ui/demo-pwa/src/page-chat.ts
ui/ui-kit/src/chat/chat-footer.ts
ui/ui-kit/src/chat/chat-text-input.ts

feat(ui-kit/chat-footer): component

---

ui/element/src/index.ts

feat(ui/element): export `unsafeHTML`

---

uniquely/soffit-pwa/src/lottery-box.ts
uniquely/soffit-pwa/src/lottery-form.ts

feat(soffit/form): expand/collapse animation

---

uniquely/soffit-pwa/src/lottery-box.ts
uniquely/soffit-pwa/src/lottery-form.ts
uniquely/soffit-pwa/src/tech-dep/radio-group.ts

feat(soffit/form): improve animation and clear extra styles

---

core/math/src/unicode-digits.ts
core/validator/src/validator.ts
ui/ui-kit/src/card/icon-box.ts
ui/ui-kit/src/text-field/text-field.ts
ui/ui-kit/tsconfig.json
uniquely/soffit-pwa/package.json
uniquely/soffit-pwa/src/lottery-box.ts
uniquely/soffit-pwa/src/lottery-form.ts
uniquely/soffit-pwa/tsconfig.json

feat(soffit-pwa): form validator and simple message

---

ui/element/src/mixins/logging.ts

feat(element): Alwatr logger index

---

ui/ui-kit/src/button/icon-button.ts
ui/ui-kit/src/top-app-bar/top-app-bar.ts
uniquely/soffit-pwa/src/alwatr-pwa.ts
uniquely/soffit-pwa/src/page-product.ts

feat(top-app-bar): new `alwatr-top-app-bar` element

---

ui/ui-kit/src/button/icon-button.ts
ui/ui-kit/src/card/product-card.ts
ui/ui-kit/src/card/surface.ts

بالاخره به یک رنگ بندی درست برای حالت انتخاب رسیدیم 👍🏻

feat(ui-kit): selectable product card

---

core/util/src/delay.ts
core/util/src/index.ts
core/util/src/polyfill.ts

codes form [paulirish](https://www.paulirish.com/2011/requestanimationframe-for-smart-animating/) and [Merten van Gerven
](https://gist.github.com/mertenvg/704cc30f419bb14bf34df9ef3083c1bf)

feat(util): polyfil requestAnimationFrame, requestIdleCallbackFallback

---

ui/element/src/mixins/router.ts

fix(router): add _routeContextUpdated to interface

---

core/type/src/type-helper.ts

refactor(type): StringifyableRecord to interface

---

core/fsm/src/core.ts

- chore(fsm): fix log
- refactor(fsm)!: add state prop and remove gotState

refactor(fsm)!: add state prop and remove gotState

---

ui/element/package.json
ui/element/src/index.ts
ui/element/src/mixins/state-machine.ts
ui/element/tsconfig.json

- feat(element): StateMachineMixin
- feat(element/fsm): add render_unresolved, render_resolving

feat(element): state mixin

---

ui/pwa-helper/esbuild.mjs
ui/pwa-helper/src/pwa-element.ts

- perf(pwa-element): scheduleUpdate by animation frame
- fix(pwa-helper): build banner

feat(pwa-helper): scheduleUpdate by animation frame in pwa-element

---

ui/ui-kit/src/button/button.ts
ui/ui-kit/src/text-field/text-field.ts

- feat(button): icon style
- fix(text-field): make it inline

fix(ui-kit): icon button styles

---

core/type/src/type-helper.ts

- feat(type): MaybeArray
- feat(type): SingleOrArray, Prop, Values, Merge
- feat(type): ArrayItems

feat(type): new type helpers

---

core/signal/src/core.ts
core/signal/src/requestable-context-consumer.ts
core/signal/src/requestable-context-provider.ts
core/signal/src/type.ts

- feat(signal): new RequestableContext with state
- fix(signal): requestableContextProvider.getValue

feat(signal): new RequestableContext with state

---

ui/icon/src/icon.ts
ui/ui-kit/src/button/icon-button.ts

- fix(icon): render delay on icon change
- fix(icon-button): disable bug

feat(icon,icon-button): issues

---

core/fsm/src/core.ts

Co-authored-by: Mohammad Honarvar <honarvar.info@gmail.com>

fix(fsm): initial exec actions

---

core/fetch/src/fetch.ts
core/fetch/src/type.ts
core/storage-client/src/storage-client.ts

- fix(fetch): bodyJson type
- feat(fetch): StringifyableFetchOptions type
- fix(fetch): serviceRequest generic type
- fix(storage-client): serviceRequest type

feat(fetch): enhance types and add StringifyableFetchOptions

---

core/type/src/service-response.ts
core/type/src/storage.ts

- fix(type/service-response): default generics
- refactor(type): AlwatrDocumentStorage type with AlwatrServiceResponseSuccessWithMeta

refactor(type): AlwatrDocumentStorage type with AlwatrServiceResponseSuccessWithMeta

---

core/context/src/core.ts

Co-authored-by: Mohammad Honarvar <honarvar.info@gmail.com>
Co-authored-by: S. Amir Mohammad Najafi <njfamirm@gmail.com>

fix(context): merge request option issue

---

demo/icon/index.ts
ui/icon/src/icon.ts

feat(ui/icon): svg property

---

core/fetch/src/fetch.ts

fix(fetch): compatible with node

---

cloud/container/nginx-storage/.dockerignore
cloud/container/nginx-storage/Dockerfile
cloud/container/nginx-storage/_error.json
cloud/container/nginx-storage/conf/location.d/10-error-page.conf.template

feat(container/nginx-storage): error.json for error

---

core/util/src/local-storage.ts

feat(util): setLocalStorageItem

---

core/type/src/customer-order-management.ts
core/type/src/user.ts

- feat(type): user permissions
- feat(type): UserAuth
- feat(type/com): ComUser/permissions

feat(type): UserAuth and user.permissions

---

.eslintrc.json
core/util/src/node/_logger.ts
core/util/src/node/fs.ts
core/util/src/node/index.ts
demo/es-bench/node-exist.ts

- feat(es-bench): test node exist methods
- feat(util): readJsonFileSync
- feat(util): readJsonFile
- feat(util): writeJsonFileSync
- feat(util): writeJsonFile

feat(util): node read write json helper methods

---

core/storage-client/src/storage-client.ts
services/storage-server/demo.http
services/storage-server/package.json
services/storage-server/src/index.ts
services/storage-server/src/route/cache-api-response.ts
services/storage-server/tsconfig.json

- feat(storage-client): `cacheApiResponse` method
- feat(storage-server): `cache-api-response` route

feat(storage-client/server): cacheApiResponse method

---

cloud/container/nginx-storage/.dockerignore
cloud/container/nginx-storage/Dockerfile
cloud/container/nginx-storage/_404.json
cloud/container/nginx-storage/_error.json
cloud/container/nginx-storage/conf/location.d/10-error-page.conf.template
cloud/container/nginx-storage/conf/location.d/40-json.conf.template
cloud/container/nginx-storage/conf/location.d/90-json.conf.template
cloud/container/nginx-storage/index.json

- fix(nginx-storage): content of static files
- feat(nginx-storage): new strategy for private storage behind auth token

feat(nginx-storage): new strategy for private storage behind auth token

---

core/fetch/src/fetch.ts
core/fetch/src/type.ts
core/type/src/user.ts

- fix(fetch): userAuth in StringifyableFetchOptions
- refactor(fetch): use delay from util

refactor(fetch): use delay from util

---

core/crypto/src/hash.ts
core/crypto/src/index.ts
core/crypto/src/pre-config.ts
core/crypto/src/user.ts
demo/crypto/rand.ts
demo/crypto/user.ts
uniquely/com-api/src/lib/config.ts
uniquely/com-api/src/lib/crypto.ts

- perf(crypto/hash): enhance crc generator
- feat(crypto): add some pre config
- refactor(crypto): use pre configs

feat(crypto): add some pre config

---

core/type/src/user.ts
uniquely/com-api/src/lib/patch-user.ts
uniquely/com-api/src/root-user.ts
uniquely/com-api/src/route/patch-user.ts

- feat(type/user): add token!
- refactor(com-api): use user.token and prevent to save it in user-list storage

feat(com-api): new user.token, prevent to save it in user-list storage

---

cloud/container/nginx-storage/conf/location.d/40-json.conf.template

feat(nginx): add hub and vault folder

---

core/storage-engine/src/storage-engine.ts
core/util/package.json
core/util/src/flat-str.ts
core/util/src/index.ts
core/util/src/node/_logger.ts
core/util/src/node/fs.ts
demo/es-bench/bench.ts
demo/es-bench/flat-str.ts
demo/storage-client/benchmark.ts
demo/storage-engine/benchmark.ts
services/storage-server/src/route/cache-api-response.ts
services/storage-server/src/route/link.ts
yarn.lock

- feat(util): flatStr
- refactor(util): node/fs with flastStr
- feat(es-bench): enhance with optional count and warning
- feat(es-bench): test flatStr

feat(util): flatStr

---

demo/es-bench/bench.ts
demo/es-bench/index.html
demo/es-bench/object-vs-map.ts

- fix(es-bench): bench calc issue
- feat(es-bench): worker

fix(es-bench): bench calc issue

---

services/comment/package.json
services/flight-crawler/package.json
services/form-registration/package.json
services/storage-server/package.json
services/telegram-notifier/package.json
ui/demo-pwa/package.json
uniquely/com-api/package.json
uniquely/com-pwa/package.json
uniquely/flight-finder-api/package.json
uniquely/keep-pwa/package.json
uniquely/soffit-pwa/package.json
yarn.lock

Fix fucking esbuild issue https://github.com/evanw/esbuild/issues/3164

hotfix: esbuild

---

.github/workflows/publish-special-container.yml
cloud/container/wordpress/php7.4/Dockerfile

[latest](https://hub.docker.com/_/wordpress/tags?page=1&name=-php7.) version support php v7 is 6.1.1

bugfix(cloud): change wordpress version

---

core/fract/package.json
core/fract/src/directives/map.ts
core/fract/src/directives/observe.ts
core/fract/src/index.ts
core/fract/src/lit-html.ts
core/fract/tsconfig.json

feat(fract): AlwatrObserveDirective

feat(fract): AlwatrObserveDirective

---

ui/icon/package.json
ui/ui-kit/src/icon/icon.scss
ui/ui-kit/src/icon/icon.ts

- fix(icon): scg export
- feat(icon2): flipIconInRtl

feat(icon2): flip icon in rtl

---

ui/ui-kit/icon/icon.scss
ui/ui-kit/navigation-bar2/navigation-bar.scss
ui/ui-kit/package.json
ui/ui-kit/src/navigation-bar/context.ts
ui/ui-kit/src/navigation-bar/navigation-bar.ts
ui/ui-kit/src/navigation-bar2/navigation-bar.scss
ui/ui-kit/src/navigation-bar2/navigation-bar.ts
ui/ui-kit/src/navigation-bar2/type.ts
ui/ui-kit/src/top-app-bar2/top-app-bar.scss
ui/ui-kit/src/top-app-bar2/top-app-bar.ts
ui/ui-kit/src/top-app-bar2/type.ts
ui/ui-kit/top-app-bar2/top-app-bar.scss

- feat(alwatrNavigationBar): new ui directive
- feat(alwatrTopAppBar): new ui directive
- fix(ui-kit): build issue
- fix(ui-kit): build issue
- feat(ui-kit/navbar2): href

feat(ui-kit): new alwatrNavigationBar and alwatrTopAppBar ui directive

---

.vscode/settings.json
ui/demo-pwa/esbuild.mjs
ui/demo-pwa/res/play.html
ui/style/lib/colors.css
ui/style/lib/colors.ts
ui/style/lib/tailwind.ts
ui/style/lib/typography.ts
ui/style/lib/z-index.ts

- feat(style): update material 3 colors
- fix(style): typography fontWeight
- feat(style): add our z-index
- feat(demo-pwa): add play.html for playground

feat(style): add z-index, update colors, fix fontWeight

---

.vscode/settings.json
package.json
yarn.lock

- chore(vscode): ignoredPullRequestBranches
- chore(deps): upgrade typescript-eslint to 6.2
- chore(deps): upgrade

chore(deps): upgrade

---

ui/style/lib/screen.ts
ui/style/lib/state-layer.ts
ui/style/lib/tailwind.ts
ui/style/lib/z-index.ts

- feat(style): screen breakpoints
- feat(style): add `stateLayerPlugin`
- feat(style): enhance stateHover, stateActive
- fix(style): change backdrop to scrim

feat(style): screen breakpoints, stateLayers, scrim

---

ui/playground/app.html
ui/playground/index.html
ui/playground/navigation-rail.html

- fix(playground): navigation drawer id
- feat(playground): add navigation rail to app
- chore(playground): add app link

feat(playground): add navigation rail to app

---

ui/demo-pwa/src/icons.ts
ui/demo-pwa/src/ui/alwatr-pwa.ts

- feat(demo-pwa): move base app from playground
- feat(demo-pwa): make each part of app function
- lint(eslint): make len
- feat(demo-pwa): use alwatrIcon directive

feat(demo-pwa): move app from playground

---

cloud/classic/prepare-node/config/onix-digi/resolv.conf

- feat: add srv4 digi
- fix(prepare-node): keyscan for multi port
- feat(prepare-node): srv4 dns

feat(prepare-node): srv4 resolve
